api/app/transaction/__init__.py
from flask import Blueprint

# Blueprint Configuration
transaction_bp = Blueprint(
    'transaction_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

from . import routes

api/app/transaction/routes.py
from api.app import mongodb
from api.app.transaction import transaction_bp
from api.app.forms.form_models import new_transaction_model
import plotly.express as px
import plotly.graph_objs as go
import pandas as pd
from flask import render_template, request, redirect, url_for, make_response
import json
import plotly
from plotly.graph_objs import *
import docx
import io
import matplotlib.pyplot as plt
from helpers.cf_analytics import update_cf, date_adj
import datetime as dt
from gridfs import GridFS
from helpers.function_hub import convert_pdf_to_text_sentences
from api.app import ckeditor

db = mongodb['myDatabase']
coll = db['deals']

@transaction_bp.route("/transaction/dashboard", methods = ["GET", "POST"])
def render_dashboard():

    values = {}
    liquidity = {}
    ptf_count = 0

    red = 'rgb(255,0,0)'
    blue = 'rgb(0,0,255)'

    for deals in coll.find():

        ptf_count += 1
        values[deals['asset_name']] = deals['transaction_value']
        liquidity[deals['asset_name']] = deals['liquidity_type']

    deals_ser = pd.Series(values)
    liquidity_ser = pd.Series(liquidity)
    cf_data = update_cf().sort_index(ascending=True)

    clrs = [red if x < 0 else blue for x in cf_data]

    fig = px.pie(title = 'Asset overview', values = deals_ser, names=deals_ser.index.values)
    fig.update_layout({
        'paper_bgcolor' : 'rgba(0,0,0,0)',
        'plot_bgcolor' : 'rgba(0,0,0,0)'
    })

    fig = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    fig1 = px.pie(title = 'Liquidity overview', values = liquidity_ser, names = liquidity_ser.index.values)
    fig1 = json.dumps(fig1, cls = plotly.utils.PlotlyJSONEncoder)

    fig4 = go.Bar(x = cf_data.index.values,
                  y = cf_data.values,
                  marker=dict(color = clrs))

    fig4 = go.Figure(data = fig4)
    fig4 = json.dumps(fig4, cls = plotly.utils.PlotlyJSONEncoder)

    form = new_transaction_model()

    #fig4 = px.bar(cf_data, title = 'Cashflow')
    #fig4 = json.dumps(fig4, cls=plotly.utils.PlotlyJSONEncoder)

    return render_template('dashboard.html', ckeditor = ckeditor, form = form, fig = fig, fig1 = fig1, fig4 = fig4, table = [deals_ser.to_frame().to_html(classes = 'data')])

@transaction_bp.route("/render_form", methods = ["GET", "POST"])
def render_form():

    form = new_transaction_model()
    file = None
    #form['asset_name'].data = 'FundRisQ S.A.' #to be used when pre-filling the form (for example when using a divestment icon next to each asset to prefill form with asset name & divestment flag)

    if request.method == "POST":
        fund_data = form.data.copy()
        if fund_data['transaction_type'] == 'Divestment' and fund_data['transaction_type'] > 0:
            fund_data['transaction_amount'] = - fund_data['transaction_amount']
        fund_data['asset_id'] = coll.find_one(sort = [("asset_id", -1)])['asset_id'] + 1

        file = request.files.get('upload_memo')
        a = file.filename

        #file = fund_data['upload_memo'].read()
        #with open(fund_data['upload_memo'], 'rb') as doc:
        storage = GridFS(db, 'deals')
        storage.put(file, asset_id = fund_data['asset_id'], filename = a)

        pdf = convert_pdf_to_text_sentences(file)
        db['deals.files'].update_one({'asset_id': fund_data['asset_id']}, {"$set": {'pdf_text': pdf}})

        del fund_data['upload_memo']

        coll.insert_one(fund_data)

    return render_template('new_transaction.html', form = form)

@transaction_bp.route("/download", methods = ["GET", "POST"])
def download():

    storage = GridFS(db, 'deals')
    data = storage.get_last_version('schroder-gaia---bluetrend---de.pdf')
    response = make_response(data.read())
    extension = data.filename.split('.')[-1]
    response.headers['Content-Type'] = f'application/{extension}'
    response.headers['Content-Disposition'] = f'inline; filename={data.filename}'
    return response

@transaction_bp.route("/generate_report", methods = ["GET", "POST"])
def generate_report():

    values = {}
    liquidity = {}

    document = docx.Document()

    document.add_heading('Quarterly risk report', 0)
    document.add_heading('Subfund XYZ', 2)

    document.add_paragraph('This risk report provides you with an overview of the subfund"s exposure towards market, credit, liquidity and other risks. Please contact the risk department if you have further questions')

    document.add_paragraph()
    document.add_heading('Portfolio overview', 3)

    for deals in coll.find():

        values[deals['asset_name']] = deals['transaction_value']
        liquidity[deals['asset_name']] = deals['liquidity_type']

    deals_ser = pd.Series(values)
    liquidity_ser = pd.Series(liquidity)

    memfile = io.BytesIO()
    plt.plot(deals_ser)
    plt.savefig(memfile)

    #fig = px.pie(values = deals_ser, names=deals_ser.index.values)
    p = document.add_paragraph()
    r = p.add_run()
    r.add_picture(memfile)

    document.save('riskreport.docx')
    print('Report has been generated')

    return redirect(url_for('transaction_bp.render_dashboard'))

@transaction_bp.route("/portfolio/", methods = ["GET", "POST"])
def portfolio():

    dict = {}

    form = new_transaction_model()
    fund_data = form.data.copy()

    if fund_data['funds'] != "":
        _id = fund_data['funds']
        asset_id = _id
        return redirect(url_for("transaction_bp.overview", asset_id = asset_id))

    else:

        for k in coll.find():

            dict[k['asset_name']] = {
                'Asset Value' : k['transaction_value'],
                'Location' : k['asset_loc'],
                'Asset Leverage' : k['asset_leverage'],
                'Memo': 1,
                'Asset Id': k['asset_id']
            }

        df = pd.DataFrame(dict)
        df = df.reset_index()

        return render_template('portfolio.html', column_names = df.columns.values, row_data=df.values, zip=zip, len = len(df.columns.values))

@transaction_bp.route("/overview/<asset_id>", methods = ["GET"])
def overview(asset_id):

    dict = {}
    k = coll.find_one({'asset_id': int(asset_id)})

    dict[k['asset_name']] = {
            'Asset Value' : k['transaction_value'],
            'Location' : k['asset_loc'],
            'Asset Leverage' : k['asset_leverage'],
            'Memo': 1,
            'Asset Id': k['asset_id']
        }

    df = pd.DataFrame(dict)
    df = df.reset_index()

    return render_template('portfolio.html', column_names = df.columns.values, row_data=df.values, zip=zip, len = len(df.columns.values))

@transaction_bp.route("/home", methods = ["GET", "POST"])
def home():

    dict = {}
    x = 0
    funds = coll.distinct("fund_subfund_name")
    portfolio = {}
    master_df = pd.DataFrame()

    for f in funds:
        AuM = 0
        Leverage = 0

    for deals in coll.find():
        x = deals["transaction_value"]
        for deals in coll:
            if deals['fund_subfund_name'] == f:
                AuM += deals['transaction_value']
                Leverage += deals['asset_leverage']

        portfolio[f] = {'AuM': AuM, 'Leverage': Leverage}
        df = pd.DataFrame(data = portfolio.values(), index = portfolio.keys())
        #master_df.append(df)
        master_df = pd.concat([master_df, df])

    news_coll = db['news']



    return render_template("home.html", value = x)

@transaction_bp.route("/transaction/video", methods = ["GET", "POST"])
def video():

    return render_template('video_test.html')

@transaction_bp.route("/transaction/prospectus", methods = ["GET", "POST"])
def prospectus():

    data = None
    return render_template('prospectus.html', data = data)

@transaction_bp.route("/transaction/edit_prospectus/<id>", methods = ["GET", "POST"])
def edit(id):

    coll = db['prospectus']

    data = coll.find_one({"type_id": id})["investment_strategy"]
    _id = 1#some id

    if request.method == "POST":

        amended_data = request.form.get('ckeditor')

        if amended_data != data:
            coll.update_one()

    return render_template('prospectus.html', data = data)








api/app/transaction/templates/dashboard.html
<!DOCTYPE html>
{% from "_render_field.html" import render_field, render_label_input_field %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Oversight dashboard</title>
    <style>
        .wrapper {
          display: grid;
          grid-template-columns: 900px 900px;
          grid-gap: 10px;
          background-color: #fff;
          color: #444;
}

        .box {
          background-color: #444;
          color: #fff;
          border-radius: 50px;
          padding: 20px;
          font-size: 150%;
        }

        body{
           background-color: #444;
           color: white;
        }

    </style>
</head>
<body>
        <a class="btn" href = "{{url_for('transaction_bp.render_form')}}"> Create transaction </a>
        <a class="btn" href = "{{url_for('transaction_bp.generate_report')}}"> Generate report </a>
        <a class="btn" href = "{{url_for('transaction_bp.download')}}"> Generate report </a>
        <a class="btn" href = "{{url_for('transaction_bp.portfolio')}}"> Generate report </a>

        <form action = "{{url_for('transaction_bp.portfolio', asset_id = 1)}}" method = "POST" enctype = "multipart/form-data" >

            {{ render_field(form.funds, field_class="form-control") }}

        <button class="btn btn-dark crm-calculator-btns" id="crm_btn" name="action"> Create </button>

        </form>

        <div>
        <div class = "wrapper">
        <div class = "box a"> IRR@risk
             <div id = 'chart' class = 'chart'> </div>
        </div>


        <div class = "box b"> TVPI
             <div id = 'chart1' class = 'chart'> </div>
        </div>

        <div class = "box c"> PrivateEquity IRR Premium
             <div id = 'chart2' class = 'chart'> </div>
        </div>

        <div class = "box d"> Cashflow
             <div id = 'chart3' class = 'chart'> </div>
        </div>


</body>

<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script type='text/javascript'>
  var graphs = {{fig | safe}};
  var graphs1 = {{fig1 | safe}};
  var graphs2 = {{fig | safe}};
  var graphs3=  {{fig4 | safe}};

  Plotly.plot('chart',graphs, {});
  Plotly.plot('chart1', graphs1, {});
  Plotly.plot('chart2', graphs2, {});
  Plotly.plot('chart3', graphs3, {});


</script>

</html>

api/app/transaction/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>

    <style>
    *{
      margin:0;
      padding:0;
      box-sizing:border-box;
    }

    html{
      background-color:#eee;
    }

    .container{
      margin: 20px auto;
      width: 800px;
      height:800px;
      background-color:#fff;
      display:grid;
      grid-template-columns: 400px 400px;
      grid-row: auto auto;
      grid-column-gap: 20px;
      grid-row-gap: 20px;
    }

    .box{
            background-color:#333;
            padding:20px;
            border-radius:20px;
            color:#fff;
            display:flex;
            align-items:center;
            justify-content:center;
            font-size:100px;
            font-family:sans-serif;
      }

    .rectangle-box{
        background-color:#333;
        padding:20px;
        border-radius:20px;
        color:#fff;
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:40px;
        font-family:sans-serif;
        width: 820px;
    }


    </style>

</head>

<body>

    <div class="container">

      <div class="box">A</div>
      <div class="box">B</div>
        <div class="rectangle-box">B</div>

    </div>

</body>

</html>

api/app/transaction/templates/new_transaction.html
<!DOCTYPE html>
{% from "_render_field.html" import render_field, render_label_input_field %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New transaction</title>
</head>
<body>

    {{ ckeditor.load()}}
    <form method = "post">
        {{ ckeditor.create() }}
        <input type ="submit">
    </form>

    <form id = 'new_transaction' action = "{{url_for('transaction_bp.render_form')}}" method = "POST" enctype = "multipart/form-data" >

        {{ render_field(form.transaction_type, field_class="form-control") }}
        {{ render_field(form.asset_name, field_class="form-control") }}
        {{ render_field(form.transaction_value, field_class="form-control") }}
        {{ render_field(form.asset_loc, field_class="form-control") }}
        {{ render_field(form.asset_leverage, field_class="form-control") }}
        {{ render_field(form.capital_call_time, field_class="form-control") }}
        {{ render_field(form.liquidity_type, field_class="form-control") }}
        {{ render_field(form.date, field_class="form-control") }}
        {{ render_field(form.upload_memo, field_class="form-control") }}


        <button class="btn btn-dark crm-calculator-btns" id="crm_btn" name="action"> Create </button>


    </form>

</body>
</html>

api/app/transaction/templates/portfolio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio Overview</title>
    <style>
    #portfolio {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#portfolio td, #portfolio th {
  border: 1px solid #ddd;
  padding: 8px;
}

#portfolio tr:nth-child(even){background-color: #f2f2f2;}

#portfolio tr:hover {background-color: #ddd;}

#portfolio th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
</head>
</style>
<body>

<table id = portfolio>

    <tr>

        {% for col in column_names %}
        <th>{{col}}</th>
        {% endfor %}
    </tr>
     {% for row in row_data %}
    <tr>
        {% for i in range(0, len) %}
        <td>
            {% if row[0] != 'Asset Id'%}
            {{row[i]}}

            {% else %}
            <a class="btn" href = "{{url_for('transaction_bp.overview', asset_id = 2)}}"> {{row[i]}} </a>
            {% endif %}
        </td>
        {% endfor %}

    </tr>
    {% endfor %}

</table>

</body>
</html>

api/app/transaction/templates/prospectus.html
<!DOCTYPE html>
{% from "_render_field.html" import render_field, render_label_input_field %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generate prospectus</title>
    <style>
        #wrapper {
            border: 1px solid blue;

            }

        #div1 {
            display: inline-block;
            width:120px;
            height: 500;
            border: 1px solid red;
            }

        #div2 {
            display: inline-block;
            width:1160px;
            height: 500px;
            border: 1px solid green;
            }
    </style>
</head>
<body>



    <div id = "wrapper">
        <div id="div1">
            <a href = "{{url_for('transaction_bp.edit', id = 'investment_strategy')}}"> Investment Objectives </a>
        </div>

        <div id = "div2">



            <form method = post enctype="multipart/form-data">
                {{ ckeditor.load() }}
                {{ ckeditor.create(value = data) }}
                <p><input type = submit value = "Save"> </p>

            </form>


        </div>
    </div>

</body>
</html>